# Template config
# Defaults are given here. If a field is not specified, its default is used.

[lastfm]
used = false
secret = "<your lastfm secret>"
user = "<your lastfm username>"
password = "<your lastfm password>"
# percent of the song that must play before scrobbles
# should be a whole number between 10 and 100
scrobble_percent = 44

[discord]
used = true
# you can override my client ID with yours if you like
client_id = "1272345557276295310"
# an image url
fallback_art = "https://files.catbox.moe/rdwkcx.png"
# an image url
small_image = "https://cdn.discordapp.com/avatars/495603896803262507/4c3f854b1aa44e41850908d06c17bd25"
# text displayed when hovering over the small image
small_text = "hiii"
# url opened when clicking on the small image
small_url = "https://github.com/tox-wtf/tuun"
# timeout in milliseconds for connecting to discord's ipc socket
timeout = 100

# hex code
# 6-char and 3-char are supported
# starting # is optional
[color]
primary = "#cdcddd"
secondary = "#333333"
tertiary = "#e5e5f5"

[general]
shuffle = true

# a list of artists whose names contain commas
artists_with_commas = [
    "Tyler, The Creator",
    "Everything, Now!",
    "Wow, Owls!",
    "Go Robot, Go!",
    "What Price, Wonderland?",
    "Hey, Revolution!",
]

# `$HOME` and `~` are the only path expansions allowed
# music_dir = "~/Music"

# if playlist is not specified, /tmp/tuun/all.tpl is used
# a tpl file is just a plain-text new-line-delimited list of absolute paths
# playlist = "~/Music/playlists/sweet breaks.tpl"

# how many songs /tmp/tuun/recent.tpl should consist of
recent_length = 350
# milliseconds to wait when polling mpv's socket on launch
mpv_socket_poll_timeout = 96
# milliseconds to wait before making discord and lastfm API calls to set now
# playing status
now_playing_delay = 2345
